### ISSUE TITLE
Desktop shortcuts not working?

### ISSUE THREAD

**Issue by WheezyE** [WheezyE/Winelink#12]
I've noticed with wine-devel 6.19 that the desktop shortcuts for RMS Express, VARA HF, and VARA FM, seem to not be working(?).  I'm going to investigate that soon.

Workaround: In the meantime, these programs all launch just fine by navigating to the wine directory where they are installed (`cd ~/.wine/drive_c/RMS\ Express/` or `cd ~/.wine/drive_c/VARA/`) and running them directly from the terminal (`wine VARA.exe` or `wine RMS\ Express.exe` for example).

**Comment by PD7RON** [comment]
Hello Eric
When I install the last version it is ending with RMS Express started and working. Everything works ok and there is no problem in using vara fm. But when I close the program and start it again then it is not possible to get it up and running. I am using the terminal as you explained it. But I am getting the message dat there is no way to start it because it has a wrong structure. 
The only way to start it, is installing the whole again so that at the end RMS Express is working.
What goes wrong when I try to start it again after closing?

73 RON
PD7RON

**Comment by WheezyE** [comment]
Thank you for testing things. Have you installed Winelink in the past? I’ve been wondering what might be causing this problem myself but not sure yet (haven’t had enough time to investigate yet).

I suspect it might be something to do with the way Wine 6.19 handles shortcuts. It might also be old wine shortcuts (installed previously) being used in a new version of wine and not working.

This should be an easy fix (see workaround above, for example - these commands could be made into a short desktop script), but I want to see if I can make the shortcuts work the way they’re supposed to instead of relying on desktop scripts.

**Comment by WheezyE** [comment]
Just wanted to post an update that I've added some desktop scripts as a workaround for now. Still haven't gotten much time to investigate these desktop shortcut errors.

**Comment by WheezyE** [comment]
Desktop shortcuts have been fixed! Apologies for the delays.
