### ISSUE TITLE
can't connect to VARA HF

### ISSUE THREAD

**Issue by yoramrotbach** [WheezyE/Winelink#2]
Hi,

In RMS, after starting a VARA HF session, I'm getting an error that the TNC isn't available in 127.0.0.1 8300
I guess this is related somehow to the overall networking issue, however it looks from the screenshots like you have passed this point.
In addition VARA will not launch stand alone.

Running on RPI 400 with latest Raspbian updates.

73
Yoram 4Z1YR

**Comment by WheezyE** [comment]
Hey!  Thanks for checking out the project.  Things are still kind of unstable at this early stage.

I haven't tested Pi 400 with Box86 myself, but I've heard that it should work (at least, TwisterOS users have been able to install Twister OS on Pi 400 and use Box86 without issues - Box86 comes preinstalled on TwisterOS).

I'm running a Pi 4 (2GB). I have been able to get VARA to launch from within an RMS Express VARA HF session on my end and at least play some tones (I haven't actually tested a full connection yet).  I think since we're just connecting to localhost, the internet issues won't matter here.  There is also a graphics glitch that keeps VARA minimized for now when run through RMS Express that I need to sort out soon, but that shouldn't affect your connection to localhost.

It sounds like VARA just isn't launching.  I do know that sometimes VARA and RMS Express get stuck after a crash in Wine and then won't open anymore.  You might try opening a new terminal window, typing in `wineserver -k` (to restart the wine listening server), hitting enter, then trying to run RMS Express (and launch VARA) again.

73 KI7POL
