### ISSUE TITLE
FYI on VarAC

### ISSUE THREAD

**Issue by km4ack** [WheezyE/Winelink#46]
https://www.varac-hamradio.com/forum/varac-discussion-forum/running-on-wine-raspberry64

**Comment by WheezyE** [comment]
Interesting! I tried this a while back and it didn’t work. I’ll look into this again. Reading through the KM4ACK forums, it looks like users may have better luck on bullseye than buster?
Thanks for the tip

**Comment by km4ack** [comment]
I haven't tried it on either but an educated guess is that Bullseye will be required.

**Comment by WheezyE** [comment]
I know we corresponded a bit by email where I tested this and got a frozen window, but I got a chance to look at this link again and it really does seem like other people are getting this running.  I'd like to upgrade box86 to a more stable version and need to bisect commits to find the VARA TCP/IP bug in the newer box86's to do that, but I think this could be a feature to implement at some point. Thank you again for brining it to my attention.

**Comment by km4ack** [comment]
Thanks for the update and your continued work on this project.

**Comment by WheezyE** [comment]
The VARA TCP/IP has been fixed with https://github.com/ptitSeb/box86/commit/26a6eb192231410772bf3c4aefaa4e05fe0c6949 (the VARA port-closing issue is still a problem though). I haven't been able to get VarAC running at all though. I'll keep and eye on this and also maybe send it over to Seb if I can't get any farther.

I'll close this for now too to consolidate responses into this issue ticket: https://github.com/WheezyE/Winelink/issues/27
