### ISSUE TITLE
Install fails on a rasbpberry pi 5

### ISSUE THREAD

**Issue by birtej** [WheezyE/Winelink#82]
After failing to remove 5 vara files from my profile ther error is :

"ERROR: Unable to parse Raspberry Pi processor type code."

If you need me to run something to identify the string returned, please let me know.

**Comment by SpudGunMan** [comment]
needs some proc data `c04170`

```
"17")PI_TYPE="CM5"
"4")PI_PROCESSOR="BCM2712"
```

**Comment by mcmonagle101** [comment]
Created an edited script that is attached.
[test.tar.gz](https://github.com/WheezyE/Winelink/files/13763074/test.tar.gz)
I think the reason  'kernel=kernel8.img'  is needed is because of box86.
Maybe if there was a version for pi 5 it would not be needed.

Seems to work so far. Still need to configure rms express.

**Comment by WheezyE** [comment]
I've updated Winelink to include [revision codes](https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc#new-style-revision-codes) for Raspberry Pi 5 (`TTTTTTTT` = type `17` "5") be2c8eec51623a10b85787b7d45468b2a359b0ad

I don't have a Pi5 to test with, but it should work. Please feel free to re-open if you have any more problems with Pi5.
